export const CommandType = {
  REGISTER_FACTORY: 'REGISTER_FACTORY',
  START_FACTORY: 'START_FACTORY',
  STOP_FACTORY: 'STOP_FACTORY',
  RESET_FACTORY: 'RESET_FACTORY',
  ASSIGN_WORKER: 'ASSIGN_WORKER',
  UNASSIGN_WORKER: 'UNASSIGN_WORKER',
  INCREASE_OUTPUT: 'INCREASE_OUTPUT',
  DECREASE_OUTPUT: 'DECREASE_OUTPUT',
} as const;

export type CommandType = typeof CommandType[keyof typeof CommandType];
